Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provider 'virtualbox' do |vm|
    vm.memory = 1024
    vm.cpus = 1
  end

  (1..3).each do |i|
    config.vm.define "vm#{i}" do |node|
      node.vm.hostname = "vm#{i}"
      node.vm.network :private_network, ip: "192.168.5.1#{i}"
    end
  end
end
